[package]
name = "conways_gol"
version = "0.1.0"
authors = ["Shivansh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
das-grid = "0.1.5"